import { Inter, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local"
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const canela = localFont({
  src: './fonts/canela.otf',
  variable: "--font-canela",
  weight: "800"
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${canela.variable} ${inter.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
